portfolio-application/app/movie_library/routes.py
import uuid
import datetime
import functools

from flask import (
    Blueprint,
    app, 
    current_app,
    render_template, 
    session, 
    redirect, 
    request, 
    url_for,
    abort,
    flash,
    Response
)
from dataclasses import asdict
from prometheus_client import generate_latest

from movie_library.forms import (
    MovieForm, 
    ExtendedMovieForm, 
    SignUpForm, 
    LoginForm
)
from movie_library.models import Movie, User
from passlib.hash import pbkdf2_sha256
from string import punctuation
from string import printable
import stringprep


pages = Blueprint(
    "pages", __name__, template_folder="templates", static_folder="static"
)

def saslprep(password):
    return ''.join(char for char in password if not stringprep.in_table_c12(char))

def login_required(route):
    @functools.wraps(route)
    def route_wrapper(*args, **kwargs):
        if session.get("email") is None:
            return redirect(url_for(".login"))

        return route(*args, **kwargs)

    return route_wrapper


@pages.route("/")
@login_required
def index():
    # Increment the HTTP request counter
    current_app.config['http_requests_total'].labels('get', '/').inc()

    current_app.logger.info(f"Fetching user data for email: {session['email']}")
    user_data = current_app.db.user.find_one({"email": session["email"]})

    # Increment the database operation counter
    current_app.config['db_operation_total'].labels('find', 'user').inc()

    current_app.logger.info(f"User data fetched: {user_data}")
    user = User(**user_data)

    current_app.logger.info("Fetching movie data...")
    movie_data = current_app.db.movie.find({"_id": {"$in": user.movies}})

    # Increment the database operation counter
    current_app.config['db_operation_total'].labels('find', 'movie').inc()

    movies = [Movie(**movie) for movie in movie_data]
    return render_template(
        "index.html",
        title="Movies Watchlist",
        movies_data=movies
    )


@pages.route("/signup", methods=["GET", "POST"])
def signUp():
    # Increment the HTTP request counter
    current_app.config['http_requests_total'].labels(request.method, '/signup').inc()

    current_app.logger.info("Accessing the signup route")
    if session.get("Email"):
        current_app.logger.info("User already logged in, redirecting to index")
        return redirect(url_for(".index"))
    
    form = SignUpForm()

    if form.validate_on_submit():
        current_app.logger.info(f"Form validated, creating user with email: {form.email.data}")

        # Sanitize password before hashing
        raw_password = form.password.data
        sanitized_password = saslprep(raw_password)

        user = User(
            _id=uuid.uuid4().hex,
            email=form.email.data,
            password=pbkdf2_sha256.hash(sanitized_password),
        )

        # Increment the database operation counter
        current_app.config['db_operation_total'].labels('insert', 'user').inc()

        current_app.db.user.insert_one(asdict(user))
        current_app.logger.info("User registered successfully")

        flash("User registered successfully", "success")

        return redirect(url_for(".login"))

    current_app.logger.info("Rendering the signup form")
    return render_template("signup.html", title="WatchList - SignUp", form=form)


@pages.route("/login", methods=["GET", "POST"])
def login():
    # Increment the HTTP request counter
    current_app.config['http_requests_total'].labels(request.method, '/login').inc()

    current_app.logger.info("Accessing the login route")
    if session.get("email"):
        current_app.logger.info("User already logged in, redirecting to index")
        return redirect(url_for(".index"))

    form = LoginForm()

    if form.validate_on_submit():
        current_app.logger.info(f"Form validated, fetching user data for email: {form.email.data}")

        # Increment the database operation counter
        current_app.config['db_operation_total'].labels('find', 'user').inc()

        user_data = current_app.db.user.find_one({"email": form.email.data})
        if not user_data:
            current_app.logger.warning("User data not found, login credentials not correct")

            # Increment the failed logins counter
            current_app.config['failed_logins_total'].inc()

            flash("Login credentials not correct", category="danger")
            return redirect(url_for(".login"))
        current_app.logger.info("User data fetched, verifying password")
        user = User(**user_data)

        if user and pbkdf2_sha256.verify(form.password.data, user.password):
            current_app.logger.info("Password verified, user logged in successfully")
            session["user_id"] = user._id
            session["email"] = user.email

            # Increment the active users gauge
            current_app.config['active_users'].inc()

            return redirect(url_for(".index"))

        current_app.logger.warning("Password verification failed, login credentials not correct")

        # Increment the failed logins counter
        current_app.config['failed_logins_total'].inc()

        flash("Login credentials not correct", category="danger")

    current_app.logger.info("Rendering the login form")
    return render_template("login.html", title="Watchlist - LogIn", form=form)


@pages.route("/logout")
def logout():
    # Increment the HTTP request counter
    current_app.config['http_requests_total'].labels('get', '/logout').inc()

    current_theme = session.get("theme")
    # session.clear()
    del session["user_id"]
    del session["email"]
    session["theme"] = current_theme

    # Decrement the active users gauge
    current_app.config['active_users'].dec()

    return redirect(url_for(".login"))


@pages.route("/add", methods=["GET", "POST"])
@login_required
def add_movie():
    # Increment the HTTP request counter
    current_app.config['http_requests_total'].labels(request.method, '/add').inc()

    current_app.logger.info("Accessing the add_movie route")
    form = MovieForm()

    if form.validate_on_submit():
        current_app.logger.info(f"Form validated, creating movie with title: {form.title.data}")
        movie = Movie(
            _id = uuid.uuid4().hex,
            title = form.title.data,
            director = form.director.data,
            year = form.year.data
        )

        # Increment the database operation counter
        current_app.config['db_operation_total'].labels('insert', 'movie').inc()

        # insert into database
        current_app.logger.info("Inserting movie into database")
        current_app.db.movie.insert_one(asdict(movie))

        # Increment the database operation counter
        current_app.config['db_operation_total'].labels('update', 'user').inc()

        current_app.logger.info("Updating user's movie list in database")
        current_app.db.user.update_one(
        {"_id": session["user_id"]}, 
        {"$push": {"movies": movie._id}}
        )

        current_app.logger.info("Movie added successfully, redirecting to index")
        return redirect(url_for(".index"))
        # return redirect(url_for(".movie", _id=movie._id))   

    current_app.logger.info("Rendering the add_movie form")
    return render_template (
        "new_movie.html",
        title = "WatchList - Add Movie",
        form = form
    )


@pages.get("/movie/<string:_id>")
def movie(_id: str):
    # Increment the HTTP request counter
    current_app.config['http_requests_total'].labels('get', '/movie/<string:_id>').inc()

    current_app.logger.info(f"Accessing the movie route for movie id: {_id}")

    # Increment the database operation counter
    current_app.config['db_operation_total'].labels('find', 'movie').inc()

    movie_data = current_app.db.movie.find_one({"_id": _id})
    if not movie_data:
        current_app.logger.warning(f"No movie found for id: {_id}, aborting with 404")
        abort(404)
    current_app.logger.info(f"Movie data fetched for id: {_id}")
    movie = Movie(**movie_data)
    current_app.logger.info("Rendering the movie_details template")
    return render_template("movie_details.html", movie=movie)


@pages.get("/movie/<string:_id>/rate")
@login_required
def rate_movie(_id):
    # Increment the HTTP request counter
    current_app.config['http_requests_total'].labels('get', '/movie/<string:_id>/rate').inc()

    current_app.logger.info(f"Accessing the rate_movie route for movie id: {_id}")
    rating = int(request.args.get("rating"))
    current_app.logger.info(f"Rating received: {rating}")

    # Increment the database operation counter
    current_app.config['db_operation_total'].labels('update', 'movie').inc()

    current_app.db.movie.update_one({"_id": _id}, {"$set": {"rating": rating}})

    # Increment the movies rated counter
    current_app.config['movies_rated_total'].inc()

    current_app.logger.info("Movie rating updated in database")

    return redirect(url_for(".movie", _id=_id))


@pages.get("/movie/<string:_id>/watch")
@login_required
def watch_today(_id):
    # Increment the HTTP request counter
    current_app.config['http_requests_total'].labels('get', '/movie/<string:_id>/watch').inc()

    current_app.logger.info(f"Accessing the watch_today route for movie id: {_id}")
    
    # Increment the database operation counter
    current_app.config['db_operation_total'].labels('update', 'movie').inc()
    
    current_app.db.movie.update_one(
        {"_id": _id}, {"$set": {"last_watched": datetime.datetime.today()}}
    )

    # Increment the movies watched counter
    current_app.config['movies_watched_total'].inc()

    current_app.logger.info("Movie last_watched date updated in database")
    return redirect(url_for(".movie", _id=_id))


@pages.route("/edit/<string:_id>", methods=["GET", "POST"])
@login_required
def edit_movie(_id: str):
    # Increment the HTTP request counter

portfolio-application/app/movie_library/templates/macros/fields.html
{% macro render_text_field(field) %}
<div class="form__group">
  {{ field.label(class_="form__label") }}
  {{ field(class_="form__field")}}

  {%- for error in field.errors %}
    <span class="form__error">{{ error }}</span>
  {% endfor %}
</div>
{% endmacro %}

{% macro render_area_field(field) %}
<div class="form__group">
  {{ field.label(class_="form__label") }}
  {{ field(rows=4, class_="form__field", style="resize: none") }}

  {%- for error in field.errors %}
  <span class="form__error">{{ error }}</span>
  {% endfor %}
</div>
{% endmacro %}

portfolio-application/app/movie_library/templates/macros/footer.html
{% macro footer() %}
<footer class="footer">
  <small>Copyright &copy; 2024. WatchList. All rights reserved.</small>
</footer>
{% endmacro %}

portfolio-application/app/movie_library/templates/macros/nav.html
{% from "macros/svgs.html" import moon, sun %}

{% macro header(email, theme) %}
<header class="header">
  <div class="nav-container">
    <a href="{{ url_for('pages.index') }}" class="header__logo">
      <?xml version="1.0" encoding="utf-8"?>
      <!-- Uploaded to: SVG Repo, www.svgrepo.com, Generator: SVG Repo Mixer Tools -->
      <svg fill="#000000" height="50px" width="50px" version="1.2" baseProfile="tiny" id="Layer_1"
        xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="-351 153 256 256"
        xml:space="preserve">
        <path id="_x31_" d="M-164.4,311.7h17.8v51h-17.8V311.7z M-136.1,311.7v51.2l39.5,17.6V294L-136.1,311.7z M-307.6,276
      	c-5.3,0-10,4.2-10,10v103c0,5.3,4.2,10,10,10h123.2c5.3,0,10-4.2,10-10V286c0-5.3-4.2-10-10-10h-11.3h-102.1H-307.6z M-298,163.6
      	c28.2,0,51,22.8,51,51s-22.8,51-51,51c-28.2,0-51-22.8-51-51S-326.2,163.6-298,163.6z M-195.8,163.6c28.2,0,51,22.8,51,51
      	s-22.8,51-51,51s-51-22.8-51-51S-224,163.6-195.8,163.6z" />
      </svg>
      <!-- <img src="{{ url_for('static', filename='icon.svg') }}" alt="Camera Icon"> -->
      <span class="logo__name">WatchList</span>
    </a>
    <nav class="nav">
      {% if not email %}
        <a href="{{ url_for('pages.login') }}" class="nav__link nav__link {{ 'nav__link--active' if request.path == url_for('pages.login') }}">
          <span class="nav__item">LogIn</span>
        </a>
        <a href="{{ url_for('pages.signUp') }}" class="nav__link {{ 'nav__link--active' if request.path == url_for('pages.signUp') }}">
          <span class="nav__item">Sign Up</span>
        </a>
      {% else %}
        <a href="{{ url_for('pages.index') }}" class="nav__link {{ 'nav__link--active' if request.path == url_for('pages.index') }}">
          <span class="nav__item">Movies</span>
        </a>
        <a href="{{ url_for('pages.logout') }}" class="nav__link">Log Out</a>
      {% endif %}
      <a href="{{ url_for('pages.toggle_theme', current_page=request.path)}}" class="nav__link">
        <span class="nav__item">
          {% if theme == "dark" %}
            {{ sun("nav__icon") }}
          {% else %}
            {{ moon("nav__icon") }}
          {% endif %}
        </span>
      </a>
    </nav>
  </div>
</header>
{% endmacro %}

portfolio-application/app/movie_library/templates/macros/svgs.html
{% macro star(class_) %}
<svg xmlns="http://www.w3.org/2000/svg" class="{{ class_ }}" viewBox="0 0 24 24" stroke="currentColor">
  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
    d="M11.049 2.927c.3-.921 1.603-.921 1.902 0l1.519 4.674a1 1 0 00.95.69h4.915c.969 0 1.371 1.24.588 1.81l-3.976 2.888a1 1 0 00-.363 1.118l1.518 4.674c.3.922-.755 1.688-1.538 1.118l-3.976-2.888a1 1 0 00-1.176 0l-3.976 2.888c-.783.57-1.838-.197-1.538-1.118l1.518-4.674a1 1 0 00-.363-1.118l-3.976-2.888c-.784-.57-.38-1.81.588-1.81h4.914a1 1 0 00.951-.69l1.519-4.674z" />
</svg>
{% endmacro %}

{% macro pencil(class_) %}
<svg xmlns="http://www.w3.org/2000/svg" class="{{ class_ }}" fill="none" viewBox="0 0 24 24" stroke="currentColor">
  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
    d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
</svg>
{% endmacro %}

{% macro moon(class_) %}
<svg xmlns="http://www.w3.org/2000/svg" class="{{ class_ }}" fill="none" viewBox="0 0 24 24" stroke="currentColor">
  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
    d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z" />
</svg>
{% endmacro %}

{% macro sun(class_) %}
<svg xmlns="http://www.w3.org/2000/svg" class="{{ class_ }}" fill="none" viewBox="0 0 24 24" stroke="currentColor">
  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
    d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z" />
</svg>
{% endmacro %}